Repository teemtee/tmt, pull requests merged in 2019-10, with the labels that each got.

#11 Propose implementing hands-free debugging
  docs/dreams.rst
Labels: documentation

#12 Add core option --debug
  stories/core.fmf
Labels: story

#13 Suggest git-like moving forward in tasks
  stories/cli.fmf
Labels: story

#17 Fix force option help
  tmt/cli.py
Labels: bug

#24 Execute: Add run.sh for running the tests on guest.
  tmt/steps/execute/run.sh
Labels: plugins
