Repository teemtee/tmt, pull requests merged in 2019-11, with the labels that each got.

#42 Add a __main__.py
  __main__.py
Labels: enhancement

#45 Import examples provided by @psss
  docs/commands.rst
  stories/cli/plan.fmf
  stories/cli/story.fmf
  stories/cli/test.fmf
Labels: documentation

#51 test_provision: fix to work with older mock
  tests/unit/steps/test_provision.py
Labels: tests
