Repository teemtee/tmt, pull requests merged in 2020-12, with the labels that each got.

#466 Store the whole debug log in the top run directory
  tmt/utils.py
Labels: logging

#480 Explain the difference between fmf and tmt
  docs/questions.rst
Labels: documentation

#483 Document the display and html report in the spec
  spec/steps/report.fmf
Labels: specification

#377 Support short options for selecting tests & plans
  tests/plan/select/main.fmf
  tests/plan/select/test.sh
  tests/test/select/main.fmf
  tests/test/select/test.sh
  tmt/cli.py
Labels: enhancement, tmt plan, tmt run, tmt story, tmt test

#484 Implement conversion between relevancy and adjust
  Makefile
  tests/test/lint/data/.fmf/version
  tests/test/lint/data/bad.fmf
  tests/test/lint/data/good.fmf
  tests/test/lint/data/perfect.fmf
  tests/test/lint/data/relevancy-list.fmf
  tests/test/lint/data/relevancy-text.fmf
  tests/test/lint/test.sh
  tests/unit/test_adjust.py
  tmt/base.py
  tmt/cli.py
  tmt/convert.py
Labels: context

#468 Import header and footer from Nitrate
  tmt/convert.py
Labels: enhancement, import

#474 Skip import of manual cases with script
  tmt/cli.py
  tmt/convert.py
Labels: enhancement, import

#485 Mark implemented
  spec/core/adjust.fmf
  spec/core/description.fmf
  spec/steps/finish.fmf
  stories/install.fmf
Labels: documentation

#489 Release tmt-1.2
  tmt.spec
Labels: packaging

#491 Remove the remaining test case relevancy leftovers
  docs/examples.rst
  docs/questions.rst
  spec/steps/discover.fmf
  spec/steps/provision.fmf
  stories/cli/test.fmf
  tmt/convert.py
  tmt/export.py
Labels: bug, context

#493 Define framework for all beakerlib libraries tests
  tests/discover/libraries/data/apache.fmf
  tests/discover/libraries/data/certificate.fmf
  tests/discover/libraries/data/main.fmf
Labels: libraries, tests

#488 Manual state for manual nitrate tests
  tmt/convert.py
Labels: import, tests

#494 Enable debug output using the TMT_DEBUG variable
  README.rst
  tests/core/env/main.fmf
  tests/core/env/test.sh
  tmt/utils.py
Labels: cli
