Repository teemtee/tmt, pull requests merged in 2020-02, with the labels that each got.

#97 Add different summaries for sub-packages
  tmt.spec
Labels: enhancement, packaging

#98 Add user story for restraint
  stories/cli/run.fmf
Labels: execute, stories

#102 Update the test case relevancy specification
  spec/tests/relevancy.fmf
Labels: specification

#111 Make it possible to pass script on cmdline
  tmt/cli.py
  tmt/steps/discover/__init__.py
Labels: enhancement, execute

#112 Fail nicely if executed without provision
  tmt/steps/execute/__init__.py
  tmt/steps/provision/podman.py
Labels: enhancement, provision

#113 Read requires as list when converting tests
  tmt/convert.py
Labels: import

#115 Read 'components' from nitrate when converting
  tmt/convert.py
Labels: enhancement, import

#130 Move container plan to common provision examples
  plans/container.fmf
  plans/main.fmf
Labels: tests

#128 Prefix all non-specification keys [fix #120]
  tmt/cli.py
  tmt/convert.py
Labels: import

#129 Remove copr build job from packit (not necessary)
  .packit.yaml
Labels: tests
