Repository teemtee/tmt, pull requests merged in 2020-01, with the labels that each got.

#67 Put quotes in `pip install .[*]` in README
  README.rst
Labels: documentation

#64 Depend on git-core and not the full git package
  tmt.spec
Labels: packaging

#72 Become root using sudo for localhost ansible runs.
  tests/unit/steps/test_provision.py
  tmt/steps/provision/localhost.py
Labels: prepare

#80 Implement test discover from execute shell script
  spec/steps/execute.fmf
  tmt/steps/discover/__init__.py
Labels: discover, enhancement, execute

#78 Create fmf for each tcms case when converting.
  tmt/cli.py
  tmt/convert.py
Labels: enhancement

#79 Add the 'requires' attribute into the L1 Metadata
  spec/tests/require.fmf
Labels: enhancement, specification

#83 Add a story for exporting tests into nitrate
  stories/cli/test.fmf
Labels: export, stories

#92 Fix deduplication bug when converting tests
  tmt/convert.py
Labels: bug, import

#91 Read more attributes from nitrate when converting
  tmt/convert.py
Labels: enhancement, import

#90 Update examples doc for converting tests
  docs/examples.rst
Labels: documentation, import

#94 tests: cruncher now supports local tests
  plans/basic.fmf
Labels: tests

#89 Optional attributes when converting.
  tmt/convert.py
Labels: enhancement, import
