Repository teemtee/tmt, pull requests merged in 2020-08, with the labels that each got.

#318 Document multiple configs and extending steps
  docs/examples.rst
Labels: documentation

#322 Append dots to fix tmt run --help message summary
  tmt/steps/discover/__init__.py
  tmt/steps/execute/__init__.py
  tmt/steps/finish/__init__.py
  tmt/steps/prepare/__init__.py
  tmt/steps/provision/__init__.py
  tmt/steps/report/__init__.py
Labels: documentation, enhancement

#249 Simplify packit custom create archive command
  .packit.yaml
  Makefile
Labels: tests

#320 Detect beakerlib libraries from recommend as well
  spec/tests/recommend.fmf
  tests/discover/libraries/data/apache.sh
  tests/discover/libraries/data/certificate.fmf
  tests/discover/libraries/data/certificate.sh
  tests/discover/libraries/data/plan.fmf
  tests/discover/libraries/test.sh
  tmt/beakerlib.py
  tmt/steps/discover/fmf.py
Labels: discover, enhancement

#324 Remove vagrant from tmt-all recommended packages
  tmt.spec
Labels: packaging

#313 Improve the maximum test duration handling
  spec/steps/discover.fmf
  spec/steps/execute.fmf
  spec/tests/duration.fmf
  tests/discover/duration/data/.fmf/version
  tests/discover/duration/data/plan.fmf
  tests/discover/duration/data/test.fmf
  tests/discover/duration/main.fmf
  tests/discover/duration/test.sh
  tests/execute/duration/data/.fmf/version
  tests/execute/duration/data/plan.fmf
  tests/execute/duration/data/test.fmf
  tests/execute/duration/main.fmf
  tests/execute/duration/test.sh
  tests/unit/test_utils.py
  tmt/base.py
  tmt/steps/discover/__init__.py
  tmt/steps/discover/shell.py
  tmt/steps/execute/__init__.py
  tmt/steps/execute/internal.py
  tmt/steps/execute/run.sh
  tmt/utils.py
Labels: enhancement, execute, specification

#331 Prevent koji from trying to build packages on i686
  tmt.spec
Labels: packaging

#327 Avoid double fmf extension when creating plans and stories
  tests/plan/create/test.sh
  tests/story/create/main.fmf
  tests/story/create/test.sh
  tmt/base.py
Labels: tmt plan, tmt story

#328 Retry requests in case of network failure
  tmt/steps/provision/minute.py
  tmt/steps/provision/testcloud.py
  tmt/utils.py
Labels: enhancement, provision
