Repository teemtee/tmt, pull requests merged in 2021-12, with the labels that each got.

#962 Release tmt-1.9.0
  tmt.spec
Labels: packaging

#900 Add support for ssh multiplexing
  tmt/steps/provision/__init__.py
  tmt/steps/provision/testcloud.py
Labels: provision, must

#974 Improve environment variables specification a bit
  spec/plans/environment.fmf
  spec/tests/environment.fmf
Labels: specification

#970 Add `bios.method` to hardware spec
  spec/plans/provision.fmf
Labels: specification, hardware

#979 Update test debugging examples with --force option
  docs/examples.rst
Labels: documentation

#984 Set the `TMT_TREE` variable during test execution
  README.rst
  tests/run/worktree/data/tree/.fmf/version
  tests/run/worktree/data/tree/file.txt
  tests/run/worktree/data/tree/plan.fmf
  tests/run/worktree/data/tree/test/main.fmf
  tests/run/worktree/test.sh
  tmt/steps/execute/internal.py
Labels: execute, environment
