Repository teemtee/tmt, pull requests merged in 2021-05, with the labels that each got.

#769 Update default option values for verbose and debug
  tmt/options.py
Labels: base, must

#770 Fix EPEL installation instructions
  README.rst
Labels: documentation

#772 Clarify that `adjust` needs explicit `context` in the documentation
  spec/core/adjust.fmf
  spec/plans/provision.fmf
Labels: documentation

#745 Give a warning about the obsoleted minute plugin
  tmt/steps/provision/minute_obsolete.py
Labels: blocked, minute, provision

#773 Enable a few more pre-commit hooks, sort imports
  .pre-commit-config.yaml
  docs/conf.py
  docs/examples.rst
  examples/vagrant/Vagrantfile.real_prod
  examples/vagrant/Vagrantfile.various
  setup.py
  tests/integration/__init__.py
  tests/integration/test_nitrate.py
  tests/prepare/adjust/data/smoke.py
  tests/prepare/freeze/test.sh
  tests/test/lint/data/bad-attribute.fmf
  tests/unit/test_utils.py
  tmt/__init__.py
  tmt/__main__.py
  tmt/base.py
  tmt/beakerlib.py
  tmt/convert.py
  tmt/export.py
  tmt/plugins.py
  tmt/steps/discover/shell.py
  tmt/steps/finish/__init__.py
  tmt/steps/finish/shell.py
  tmt/steps/prepare/__init__.py
  tmt/steps/prepare/shell.py
  tmt/steps/provision/minute_obsolete.py
  tmt/steps/provision/testcloud.py
  tmt/steps/report/html.py
  tmt/utils.py
Labels: style

#698 Add import warning if Makefile has skipped targets
  tmt/convert.py
Labels: import, tests

#767 Add a simple example of a test written in ansible
  examples/ansible/.fmf/version
  examples/ansible/plan.fmf
  examples/ansible/test.fmf
  examples/ansible/test.yml
Labels: documentation

#730 Support fetching libraries from local directory
  spec/tests/require.fmf
  tests/libraries/local/data/.fmf/version
  tests/libraries/local/data/main.fmf
  tests/libraries/local/data/test.sh
  tests/libraries/local/main.fmf
  tests/libraries/local/test.sh
  tmt/beakerlib.py
Labels: libraries

#777 Propagate options to guests based on the step
  tests/core/debug/data/.fmf/version
  tests/core/debug/data/main.fmf
  tests/core/debug/main.fmf
  tests/core/debug/test.sh
  tmt/steps/finish/__init__.py
  tmt/steps/prepare/__init__.py
Labels: finish, prepare

#786 Fix option handling for plugins with common prefix
  tmt/options.py
Labels: cli, plugins

#779 Hand over plan environment during local execution
  tests/core/env/data/main.fmf
  tmt/steps/provision/local.py
Labels: execute, prepare

#780 Use debuginfo-install for debuginfo packages
  tests/prepare/install/data/debuginfo.fmf
  tests/prepare/install/test.sh
  tmt/steps/prepare/install.py
Labels: prepare

#784 Add option to explicitly use default plan
  tests/run/default/test.sh
  tmt/base.py
  tmt/cli.py
Labels: plans

#791 Use `count=True` for multiple flag options
  tmt/options.py
  tmt/utils.py
Labels: cli

#717 Print better error when nitrate testcase not found.
  tmt/export.py
Labels: export, nitrate
