Repository teemtee/tmt, pull requests merged in 2022-08, with the labels that each got.

#1149 Cut circular dependency of libraries.
  tests/libraries/recursion/data/lib.sh
  tests/libraries/recursion/data/test.sh
  tests/libraries/recursion/main.fmf
  tests/libraries/recursion/test.sh
  tmt/beakerlib.py
Labels: libraries

#1397 Use textwrap.dedent() to unindent docstrings
  tmt/steps/__init__.py
Labels: code style

#1398 Rename "default how" step attribute to enhance its visibility
  tmt/steps/__init__.py
  tmt/steps/execute/__init__.py
  tmt/steps/provision/__init__.py
  tmt/steps/report/__init__.py
Labels: code style

#1410 Correcting rhts aliases & adding rhts opt.
  tests/execute/restraint/report-log/data/log.sh
  tmt/steps/execute/internal.py
  tmt/steps/execute/scripts/tmt-file-submit
Labels: restraint

#1395 Extend plan schema with all known step plugin schemas
  tmt/schemas/plan.yaml
  tmt/utils.py
Labels: schema

#1421 Adds missing multihost keys, role and where, to schemas
  tmt/schemas/common.yaml
  tmt/schemas/execute/tmt.yaml
  tmt/schemas/execute/upgrade.yaml
  tmt/schemas/prepare/install.yaml
  tmt/schemas/provision/artemis.yaml
  tmt/schemas/provision/connect.yaml
  tmt/schemas/provision/container.yaml
  tmt/schemas/provision/local.yaml
  tmt/schemas/provision/virtual.yaml
Labels: type annotations, schema

#1268 Adds a fmf node validation layer to core classes (Test/Plan/Story)
  mypy.ini
  tests/multihost/provision/data/wrong.fmf
  tests/unit/test_schemas.py
  tmt/base.py
  tmt/schemas/common.yaml
  tmt/steps/discover/__init__.py
  tmt/templates.py
  tmt/utils.py
Labels: blocked, type annotations

#1335 Add typing for steps/discover/shell.py
  mypy.ini
  tmt/steps/discover/shell.py
Labels: type annotations

#1302 Type annotating tmt/steps/finish/__init__.py
  mypy.ini
  tmt/steps/finish/__init__.py
  tmt/steps/finish/shell.py
  tmt/utils.py
Labels: discuss, type annotations

#1423 Give a nice error for old `guests.yaml` format
  tmt/utils.py
Labels: utils

#1430 Allow numbers and booleans to be values of environment
  tmt/schemas/common.yaml
  tmt/schemas/test.yaml
Labels: schema

#1433 Display test/plan/story name in parametrized schema tests
  tests/unit/test_schemas.py
Labels: tests

#1300 Add typing for tmt/steps/finish/ansible.py
  mypy.ini
  tmt/steps/finish/ansible.py
Labels: blocked, type annotations

#1443 Add a simple hint how to write user messages
  docs/contribute.rst
Labels: documentation

#1227 Demonstrate inheritance on a virtual test example
  docs/examples.rst
Labels: documentation

#1394 Use decorator to register plugin methods
  examples/plugins/discover.py
  examples/plugins/provision.py
  tmt/steps/__init__.py
  tmt/steps/discover/__init__.py
  tmt/steps/discover/fmf.py
  tmt/steps/discover/shell.py
  tmt/steps/execute/__init__.py
  tmt/steps/execute/internal.py
  tmt/steps/execute/upgrade.py
  tmt/steps/finish/__init__.py
  tmt/steps/finish/ansible.py
  tmt/steps/finish/shell.py
  tmt/steps/prepare/__init__.py
  tmt/steps/prepare/ansible.py
  tmt/steps/prepare/install.py
  tmt/steps/prepare/multihost.py
  tmt/steps/prepare/shell.py
  tmt/steps/provision/__init__.py
  tmt/steps/provision/artemis.py
  tmt/steps/provision/connect.py
  tmt/steps/provision/local.py
  tmt/steps/provision/podman.py
  tmt/steps/provision/testcloud.py
  tmt/steps/report/__init__.py
  tmt/steps/report/display.py
  tmt/steps/report/html.py
  tmt/steps/report/junit.py
  tmt/steps/report/polarion.py
Labels: breakage, type annotations, code style

#1424 Change base fmf-backed classes to use keyword-only __init__
  tests/unit/test_base.py
  tests/unit/test_id.py
  tmt/base.py
  tmt/export.py
  tmt/steps/discover/__init__.py
  tmt/utils.py
Labels: breakage, type annotations, code style

#1445 Do not inherit classes from object
  tmt/base.py
  tmt/beakerlib.py
  tmt/utils.py
Labels: code style

#1446 Testcloud expects disk and memory to be int
  tests/provision/virtual.testcloud/data/.fmf/version
  tests/provision/virtual.testcloud/data/plan.fmf
  tests/provision/virtual.testcloud/main.fmf
  tests/provision/virtual.testcloud/test.sh
  tmt/steps/provision/testcloud.py
Labels: bug, testcloud

#1450 Ask mypy to show error codes in its messages
  mypy.ini
Labels: tests, type annotations

#1417 Annotate tmt.steps.provision
  mypy.ini
  tmt/steps/__init__.py
  tmt/steps/provision/__init__.py
  tmt/steps/provision/artemis.py
Labels: type annotations

#1453 Fixes use of SSH keys in testcloud and connect plugins
  tmt/steps/provision/connect.py
  tmt/steps/provision/testcloud.py
Labels: bug

#1426 Allow raising an exception on validation errors
  tmt/base.py
  tmt/utils.py
Labels: type annotations, code style

#1286 Type Annotating: /steps/provision/connect.py
  mypy.ini
  tmt/steps/provision/connect.py
Labels: provision, type annotations

#1427 Adds types describing tmt constructs when as stored in raw fmf data
  tmt/base.py
Labels: type annotations, code style

#1439 Remove unused keys parameter from wake() methods
  tmt/steps/__init__.py
  tmt/steps/discover/fmf.py
  tmt/steps/discover/shell.py
  tmt/steps/execute/internal.py
  tmt/steps/finish/shell.py
  tmt/steps/prepare/ansible.py
  tmt/steps/prepare/install.py
  tmt/steps/prepare/shell.py
  tmt/steps/provision/__init__.py
  tmt/steps/provision/artemis.py
  tmt/steps/provision/connect.py
  tmt/steps/provision/local.py
  tmt/steps/provision/podman.py
  tmt/steps/provision/testcloud.py
Labels: breakage, code style

#1419 Add typing for tmt/steps/provision/local.py
  mypy.ini
  tmt/steps/provision/__init__.py
  tmt/steps/provision/local.py
Labels: type annotations

#1414 Add typing for tmt/steps/provision/testcloud.py
  mypy.ini
  tmt/steps/provision/testcloud.py
Labels: type annotations

#1418 Add typing for tmt/steps/provision/podman.py
  mypy.ini
  tmt/steps/provision/podman.py
Labels: type annotations

#1415 Run tests for private plugins as well
  .packit.yaml
Labels: tests

#1435 Fixes Artemis guest data class link
  tmt/steps/provision/artemis.py
  tmt/steps/provision/local.py
Labels: bug, provision

#1178 Adds normalization layer to base classes based on fmf
  tests/test/lint/test.sh
  tests/unit/test_base.py
  tmt/base.py
  tmt/convert.py
  tmt/export.py
  tmt/steps/discover/__init__.py
  tmt/utils.py
Labels: type annotations, code style

#1381 Encapsulate created file within script's dataclass
  tmt/steps/execute/__init__.py
  tmt/steps/execute/internal.py
Labels: execute, code style, freeze

#1454 Require `libvirt-daemon-config-network` as well
  plans/provision/virtual.fmf
  tests/provision/virtual/dependencies/main.fmf
  tests/provision/virtual/dependencies/test.sh
  tmt.spec
Labels: provision, packaging, freeze

#1463 Hint user if 'tmt init' creates nested root
  tests/init/nested/main.fmf
  tests/init/nested/test.sh
  tmt/base.py
Labels: init

#1432 Report enabled/disabled plans/tests/stories via option
  tests/plan/show/data/.fmf/version
  tests/plan/show/data/plans/disabled.fmf
  tests/plan/show/data/plans/enabled.fmf
  tests/plan/show/main.fmf
  tests/plan/show/test.sh
  tests/story/show/data/.fmf/version
  tests/story/show/data/stories/disabled.fmf
  tests/story/show/data/stories/enabled.fmf
  tests/story/show/main.fmf
  tests/story/show/test.sh
  tests/test/show/data/.fmf/version
  tests/test/show/data/tests/disabled01.fmf
  tests/test/show/data/tests/disabled02.fmf
  tests/test/show/data/tests/enabled01.fmf
  tests/test/show/data/tests/enabled02.fmf
  tests/test/show/main.fmf
  tests/test/show/test.sh
  tmt/base.py
  tmt/cli.py
Labels: stories, plans, tests, cli

#1467 Fix polarion tcmscaseid search
  tmt/export.py
Labels: export, polarion

#1468 Ignore race in last-run symlink creation
  tests/unit/test_utils.py
  tmt/utils.py
Labels: config

#1431 Add link-polarion option and fix link searching bug
  tmt/cli.py
  tmt/export.py
Labels: export, polarion

#1469 Clarify motivation for creating `id` during export
  docs/questions.rst
  spec/core/id.fmf
Labels: documentation

#1434 Teach schema validation tests to peek into other trees
  tests/unit/test_schemas.py
Labels: tests

#1480 Fixes prepare/multihost docstring example to match implementation
  tmt/steps/prepare/multihost.py
Labels: prepare

#1477 Reorder step and their base plugin classes (step data conversion, part 1)
  tmt/steps/__init__.py
  tmt/steps/discover/__init__.py
  tmt/steps/execute/__init__.py
  tmt/steps/finish/__init__.py
  tmt/steps/prepare/__init__.py
  tmt/steps/provision/__init__.py
  tmt/steps/report/__init__.py
Labels: steps

#1349 Use `/bin/bash` instead of `/bin/sh` for execute
  spec/plans/finish.fmf
  spec/plans/prepare.fmf
  spec/tests/test.fmf
  tests/run/shell/data/.fmf/version
  tests/run/shell/data/reproducer.fmf
  tests/run/shell/main.fmf
  tests/run/shell/test.sh
  tmt/steps/finish/shell.py
  tmt/steps/prepare/shell.py
  tmt/utils.py
Labels: execute, utils

#1458 Move `tag` and `tier` to common core attributes
  spec/core/tag.fmf
  spec/core/tier.fmf
  spec/tests/tier.fmf
  tests/plan/show/data/plans/full.fmf
  tests/plan/show/data/plans/mini.fmf
  tests/plan/show/data/variables.yaml
  tests/plan/show/test.sh
  tests/story/show/data/stories/full.fmf
  tests/story/show/data/stories/mini.fmf
  tests/story/show/test.sh
  tests/test/show/data/tests/full.fmf
  tests/test/show/data/tests/mini.fmf
  tests/test/show/test.sh
  tmt/base.py
  tmt/schemas/core.yaml
  tmt/schemas/plan.yaml
  tmt/schemas/story.yaml
  tmt/schemas/test.yaml
Labels: stories, specification, plans, tests, core, base

#1485 Less eager to disable nitrate case
  tmt/export.py
Labels: export, tests

#1478 Moves validation and normalization mixins to utils (step data conversion, part 2)
  tmt/base.py
  tmt/utils.py
Labels: utils, base
