Repository teemtee/tmt, pull requests merged in 2022-06, with the labels that each got.

#1152 Copy the whole git repo only if necessary
  tests/core/order/test.sh
  tests/discover/no-git-needed/data/foo
  tests/discover/no-git-needed/data/tests/.fmf/version
  tests/discover/no-git-needed/data/tests/plan.fmf
  tests/discover/no-git-needed/data/tests/test.fmf
  tests/discover/no-git-needed/main.fmf
  tests/discover/no-git-needed/test.sh
  tmt/steps/discover/fmf.py
Labels: discover

#1223 Require qemu dependencies for other architectures
  tmt.spec
Labels: provision, packaging, testcloud

#1128 Dist-git-source for Discover (fmf, shell)
  README.rst
  tests/discover/data/distgit_test_plugin.py
  tests/discover/data/plans.fmf
  tests/discover/distgit.sh
  tmt/steps/discover/__init__.py
  tmt/steps/discover/fmf.py
  tmt/steps/discover/shell.py
  tmt/utils.py
Labels: discover

#1205 tmt clean should not run rsync at all
  tmt/base.py
  tmt/utils.py
Labels: clean

#1230 Release tmt-1.14.0
  tmt.spec
Labels: packaging

#1231 Add description with full test suite instructions
  docs/contribute.rst
  tests/execute/upgrade/main.fmf
  tests/full/test.fmf
  tests/prepare/main.fmf
Labels: documentation, tests

#1226 Increase `duration` for the reboot-related tests
  tests/execute/reboot/main.fmf
Labels: tests

#1206 Except nitrate xmlrpc issues during import
  tmt/convert.py
Labels: import

#1203 Add typing for multihost.py
  mypy.ini
  tmt/steps/prepare/multihost.py
Labels: type annotations

#1200 Avoid re-using image/instance for different values by testcloud plugin
  tmt/steps/provision/testcloud.py
Labels: type annotations

#1199 Introduce dataclasses as a requirement
  setup.py
  tests/unit/test_dataclasses.py
  tmt.spec
Labels: type annotations

#1244 Every subpackage must require the main tmt package
  tmt.spec
Labels: packaging

#1234 Handle missing nitrate user during export
  tests/integration/data/nitrate/existing_testcase_missing_user/main.fmf
  tests/integration/test_data/test_nitrate/NitrateExport.test_missing_user_dryrun.yaml
  tests/integration/test_nitrate.py
  tmt/export.py
Labels: export, nitrate

#1242 Tweak merging guideline, add CODEOWNERS
  .github/CODEOWNERS
  docs/contribute.rst
Labels: documentation, packaging

#1254 Exclude namespaced backup in beakerlib
  tests/pull/results/data/test.fmf
  tests/pull/results/test.sh
  tmt/steps/execute/internal.py
Labels: execute

#1202 Add JSON Schema for tests
  .pre-commit-config.yaml
  setup.py
  tests/unit/test_schemas.py
  tmt/schemas/common.yaml
  tmt/schemas/core.yaml
  tmt/schemas/test.yaml
Labels: type annotations

#1193 Add typing for steps/prepare/ansible.py
  mypy.ini
  tmt/steps/prepare/ansible.py
Labels: prepare, ansible, type annotations

#1224 Add typing for steps/prepare/shell.py
  mypy.ini
  tmt/steps/prepare/shell.py
Labels: type annotations

#1246 Adds a base class for key/value containers that can be saved and restored
  tmt/utils.py
Labels: type annotations

#1273 Detect legacy relevancy during import as well
  tests/integration/data/nitrate/import_old_relevancy/Makefile
  tests/integration/test_data/test_nitrate/NitrateImportAutomated.test_old_relevancy.yaml
  tests/integration/test_nitrate.py
  tests/unit/test_convert.py
  tmt/convert.py
Labels: import, nitrate

#1238 Add typing for plugins/__init__.py
  mypy.ini
  tmt/plugins/__init__.py
Labels: type annotations

#1221 tmt/steps/__init__.py: add typing
  .pre-commit-config.yaml
  mypy.ini
  tmt/base.py
  tmt/plugins/__init__.py
  tmt/steps/__init__.py
  tmt/steps/discover/__init__.py
  tmt/steps/execute/__init__.py
  tmt/steps/prepare/__init__.py
  tmt/steps/prepare/multihost.py
  tmt/steps/provision/__init__.py
  tmt/steps/provision/artemis.py
Labels: type annotations

#1251 Refactor internal executor scripts
  setup.py
  spec/plans/execute.fmf
  stories/features/reboot.fmf
  tmt/steps/execute/__init__.py
  tmt/steps/execute/internal.py
  tmt/steps/execute/scripts/tmt-file-submit
  tmt/steps/execute/scripts/tmt-reboot
  tmt/steps/provision/__init__.py
  tmt/steps/provision/local.py
  tmt/steps/provision/podman.py
Labels: execute

#1277 Adds support for newer Artemis API versions
  tmt/steps/provision/artemis.py
Labels: provision

#1289 Fail import for packages starting with minus sign
  tests/test/import/data/parent/negative-requires/Makefile
  tests/test/import/test.sh
  tmt/convert.py
Labels: import, tests

#1294 Use `must` for all mandatory spec requirements
  spec/core/adjust.fmf
  spec/core/enabled.fmf
  spec/core/id.fmf
  spec/core/order.fmf
  spec/core/summary.fmf
  spec/plans/context.fmf
  spec/plans/discover.fmf
  spec/plans/environment-file.fmf
  spec/plans/execute.fmf
  spec/plans/finish.fmf
  spec/plans/import.fmf
  spec/plans/prepare.fmf
  spec/plans/summary.fmf
  spec/stories/example.fmf
  spec/stories/priority.fmf
  spec/stories/title.fmf
  spec/tests/component.fmf
  spec/tests/contact.fmf
  spec/tests/description.fmf
  spec/tests/duration.fmf
  spec/tests/environment.fmf
  spec/tests/framework.fmf
  spec/tests/manual.fmf
  spec/tests/path.fmf
  spec/tests/recommend.fmf
  spec/tests/require.fmf
  spec/tests/summary.fmf
  spec/tests/tag.fmf
  spec/tests/test.fmf
Labels: specification

#1295 Rename `uuid` to `identifier` to prevent conflicts
  mypy.ini
  tests/unit/test_id.py
  tmt/base.py
  tmt/cli.py
  tmt/identifier.py
Labels: code style

#1292 Unbundle template from report.html
  setup.py
  tests/report/html/data/.fmf/version
  tests/report/html/data/main.fmf
  tests/report/html/main.fmf
  tests/report/html/test.sh
  tmt.spec
  tmt/steps/report/html.py
  tmt/steps/report/html/template.html.j2
Labels: report

#1184 Add typing for beakerlib.by
  mypy.ini
  tmt/beakerlib.py
Labels: type annotations

#1276 Check changes are pushed before export nitrate
  tests/integration/data/nitrate/validation/main.fmf
  tests/integration/test_data/test_nitrate/NitrateExport.test_export_blocked_by_validation.yaml
  tests/integration/test_data/test_nitrate/NitrateExport.test_export_forced_validation.yaml
  tests/integration/test_nitrate.py
  tests/unit/test_utils.py
  tmt/cli.py
  tmt/export.py
  tmt/utils.py
Labels: export, tests

#1290 Avoid Library url conflict if repo doesn't exist
  tests/unit/test_beakerlib.py
  tmt/beakerlib.py
Labels: libraries

#1307 Add `environment-file` to possible Plan keys
  tmt/base.py
Labels: lint

#1164 Add support for the `rpm-ostree` package manager
  tmt/steps/prepare/install.py
  tmt/utils.py
Labels: prepare

#1301 Add typing for tmt/steps/finish/shell.py
  mypy.ini
  tmt/steps/finish/shell.py
Labels: type annotations

#1309 Test import --general is default now
  docs/examples.rst
  tests/integration/test_data/test_nitrate/NitrateImportAutomated.test_basic.yaml
  tests/integration/test_nitrate.py
  tmt/cli.py
Labels: documentation, import, tests

#1308 Retry getting environment file
  tests/core/environment-file/data/main.fmf
  tests/core/environment-file/test.sh
  tmt/utils.py
Labels: plans
