Repository teemtee/tmt, pull requests merged in 2022-10, with the labels that each got.

#1552 Allow mypy to cover whole tmt.steps.prepare
  mypy.ini
Labels: type annotations

#1488 Custom results implementation
  spec/tests/result.fmf
  tests/execute/result/basic.sh
  tests/execute/result/basic/.fmf/version
  tests/execute/result/basic/test.fmf
  tests/execute/result/custom.sh
  tests/execute/result/custom/.fmf/version
  tests/execute/result/custom/results.yaml
  tests/execute/result/custom/test.fmf
  tests/execute/result/main.fmf
  tmt/base.py
  tmt/schemas/test.yaml
  tmt/steps/execute/__init__.py
  tmt/steps/execute/internal.py
  tmt/utils.py
Labels: execute, base

#1543 Print fmf tree location when schema unit test fails
  tests/unit/test_schemas.py
Labels: tests

#1522 Documents and corrects use of class conversion methods
  docs/classes.rst
  tmt/base.py
  tmt/steps/__init__.py
  tmt/steps/discover/fmf.py
  tmt/steps/discover/shell.py
  tmt/steps/provision/testcloud.py
  tmt/utils.py
Labels: documentation, code style

#1539 Ignore plan -n when searching for upgrade path
  tests/execute/upgrade/override.sh
  tmt/steps/execute/upgrade.py
Labels: bug, execute

#1525 Fixes enhancing of environment by local's guest implementation
  tmt/steps/provision/local.py
Labels: bug, provision

#1383 Add typing for steps/execute/upgrade.py
  mypy.ini
  tmt/steps/execute/upgrade.py
Labels: type annotations

#1561 Allow mypy to cover the whole tmt.plugins and tmt.steps
  mypy.ini
Labels: type annotations

#1528 Add flake8 config file for easier integration with IDEs
  .flake8
  .pre-commit-config.yaml
Labels: tests

#1547 Emit only non-default keys when constructing a test from `execute`
  tmt/steps/discover/shell.py
Labels: discover

#1570 Fix provision for coreos image
  tests/provision/virtual.testcloud/test.sh
  tmt/steps/provision/testcloud.py
Labels: provision, testcloud

#1506 Adding EFI configuration to tmt-reboot
  stories/features/reboot.fmf
  tests/execute/reboot/efi.sh
  tests/execute/reboot/efi/.fmf/version
  tests/execute/reboot/efi/plan.fmf
  tests/execute/reboot/efi/test.fmf
  tests/execute/reboot/efi/test.sh
  tests/execute/reboot/main.fmf
  tmt/steps/execute/scripts/tmt-reboot
Labels: need docs, reboot

#1564 Fix recommended packages handling for rpm-ostree
  tests/prepare/recommend/main.fmf
  tests/prepare/recommend/test.sh
  tmt/steps/prepare/install.py
Labels: prepare

#1577 Release tmt-1.18.0
  tmt.spec
Labels: packaging

#1542 Remove custom yet same implementation of step's show()
  tmt/steps/__init__.py
  tmt/steps/discover/__init__.py
  tmt/steps/execute/__init__.py
  tmt/steps/finish/__init__.py
  tmt/steps/prepare/__init__.py
  tmt/steps/provision/__init__.py
  tmt/steps/report/__init__.py
Labels: code style

#1573 Adds type annotations to tmt itself
  bin/tmt
  mypy.ini
Labels: type annotations

#1572 Fix test depending on ordering of elements in junit XML
  tests/unit/test_report_junit.py
Labels: tests

#1457 Adds type annotations to base.py
  docs/classes.rst
  docs/conf.py
  mypy.ini
  tests/discover/filtering.sh
  tests/execute/basic/test.sh
  tests/test/export/test.sh
  tests/unit/test_beakerlib.py
  tmt/base.py
  tmt/beakerlib.py
  tmt/cli.py
  tmt/convert.py
  tmt/export.py
  tmt/steps/__init__.py
  tmt/steps/discover/__init__.py
  tmt/steps/discover/fmf.py
  tmt/steps/discover/shell.py
  tmt/steps/execute/__init__.py
  tmt/steps/execute/internal.py
  tmt/steps/execute/upgrade.py
  tmt/steps/prepare/ansible.py
  tmt/steps/provision/__init__.py
  tmt/steps/provision/podman.py
  tmt/steps/report/display.py
  tmt/steps/report/html/template.html.j2
  tmt/steps/report/junit.py
  tmt/templates.py
  tmt/utils.py
Labels: blocked, breakage, type annotations, code style

#1597 Define CPU HW components with more granularity
  spec/plans/provision.fmf
  tmt/schemas/provision/hardware.yaml
Labels: documentation, provision, specification, hardware

#1555 Update all linters to their most recent versions
  .pre-commit-config.yaml
  docs/conf.py
  examples/plugins/setup.py
  setup.py
  tests/core/environment-file/data/environment_file_data.py
  tmt/base.py
  tmt/steps/__init__.py
  tmt/steps/provision/artemis.py
  tmt/utils.py
Labels: tests

#1538 Adds a missing import to polarion plugin
  tmt/steps/report/polarion.py
Labels: code style

#1588 Fix normalization of Plan.context key
  tests/plan/context/data/.fmf/version
  tests/plan/context/data/bad-values.fmf
  tests/plan/context/data/bad.fmf
  tests/plan/context/data/good.fmf
  tests/plan/context/main.fmf
  tests/plan/context/test.sh
  tests/plan/show/test.sh
  tmt/base.py
  tmt/schemas/plan.yaml
Labels: bug, type annotations

#1571 Replace GeneralError's "origin" with Python's "raise from"
  bin/tmt
  tests/unit/test_base.py
  tmt/export.py
  tmt/plugins/__init__.py
  tmt/steps/__init__.py
  tmt/steps/discover/fmf.py
  tmt/steps/discover/shell.py
  tmt/steps/execute/__init__.py
  tmt/steps/prepare/ansible.py
  tmt/steps/provision/testcloud.py
  tmt/utils.py
Labels: code style

#1593 Replaces two more list comprehensions with generators
  tmt/base.py
  tmt/steps/provision/__init__.py
Labels: code style

#1594 Use dict comprehension instead of tuple-in-list-in-dict sequence
  tmt/base.py
Labels: code style

#1595 Use enumerate() instead of range(len())
  tmt/base.py
  tmt/export.py
  tmt/options.py
Labels: code style

#1596 Use set comprehension istead of list-in-set sequence
  tmt/export.py
Labels: code style

#1598 Unblock mypy's follow-import setting
  mypy.ini
Labels: type annotations

#1604 Move Result class out of base.py
  tmt/__init__.py
  tmt/base.py
  tmt/result.py
  tmt/steps/__init__.py
  tmt/steps/execute/__init__.py
  tmt/steps/execute/internal.py
  tmt/steps/execute/upgrade.py
  tmt/steps/report/__init__.py
  tmt/steps/report/junit.py
Labels: code style

#1600 Review and annotate all cast() calls with respective issues
  tmt/base.py
  tmt/beakerlib.py
  tmt/cli.py
  tmt/convert.py
  tmt/export.py
  tmt/result.py
  tmt/steps/__init__.py
  tmt/steps/discover/__init__.py
  tmt/steps/discover/fmf.py
  tmt/steps/discover/shell.py
  tmt/steps/execute/__init__.py
  tmt/steps/execute/internal.py
  tmt/steps/execute/upgrade.py
  tmt/steps/finish/__init__.py
  tmt/steps/prepare/__init__.py
  tmt/steps/prepare/ansible.py
  tmt/steps/prepare/install.py
  tmt/steps/prepare/shell.py
  tmt/steps/provision/__init__.py
  tmt/steps/provision/artemis.py
  tmt/steps/provision/testcloud.py
  tmt/steps/report/__init__.py
  tmt/utils.py
Labels: type annotations

#1603 Review all uses of Any and refer to relevant issues
  tmt/base.py
  tmt/cli.py
  tmt/export.py
  tmt/identifier.py
  tmt/steps/__init__.py
  tmt/steps/prepare/ansible.py
  tmt/steps/prepare/install.py
  tmt/steps/prepare/shell.py
  tmt/steps/provision/artemis.py
  tmt/steps/provision/testcloud.py
  tmt/steps/report/polarion.py
  tmt/utils.py
Labels: type annotations

#1529 Enhance ClickOptionDecorator type to announce identity
  tmt/options.py
  tmt/steps/discover/__init__.py
  tmt/steps/discover/fmf.py
  tmt/steps/execute/__init__.py
  tmt/steps/execute/internal.py
  tmt/steps/execute/upgrade.py
  tmt/steps/finish/shell.py
  tmt/steps/prepare/ansible.py
  tmt/steps/prepare/install.py
  tmt/steps/prepare/shell.py
  tmt/steps/provision/artemis.py
  tmt/steps/provision/connect.py
  tmt/steps/provision/podman.py
  tmt/steps/provision/testcloud.py
  tmt/steps/report/html.py
  tmt/steps/report/junit.py
  tmt/steps/report/polarion.py
Labels: type annotations, code style

#1617 Review all uses of `type: ignore` and link relevant issues
  tmt/base.py
  tmt/cli.py
  tmt/export.py
  tmt/result.py
  tmt/steps/__init__.py
  tmt/steps/discover/shell.py
  tmt/steps/execute/upgrade.py
  tmt/steps/finish/ansible.py
  tmt/steps/prepare/ansible.py
  tmt/steps/provision/__init__.py
  tmt/steps/provision/artemis.py
  tmt/steps/provision/connect.py
  tmt/steps/provision/testcloud.py
  tmt/steps/report/junit.py
  tmt/utils.py
Labels: type annotations

#1610 Make links relative for report html
  tests/report/html/test.sh
  tmt/steps/report/html.py
  tmt/steps/report/html/template.html.j2
Labels: report, html

#1618 Fixes a typo in cpu.sockets HW requirement
  spec/plans/provision.fmf
Labels: documentation

#1620 Fix guest distro detection, do not throw results away
  tmt/steps/provision/__init__.py
Labels: bug, provision

#1623 Fixes use of variable before assignment in Plan.go
  tmt/base.py
Labels: bug

#1619 Remove pointless reimport of tmt.base in discover steps
  tmt/steps/discover/__init__.py
  tmt/steps/discover/shell.py
Labels: code style

#1625 Update the pip installation plan
  README.rst
  plans/install/pip.fmf
Labels: tests

#1580 Add message to failure tags in junit
  tests/report/junit/test.sh
  tmt/result.py
  tmt/steps/report/junit.py
Labels: report

#1627 Log full chain of exceptions, not just the first cause
  bin/tmt
Labels: cli

#1634 Fix NO_COLOR not being honored by executed command output
  tmt/utils.py
Labels: bug, logging

#1608 Adds a test for fmf id parsing and normalization
  tests/core/fmf-id/data/.fmf/version
  tests/core/fmf-id/data/plan-with-invalid-ref.fmf
  tests/core/fmf-id/data/plan-with-valid-ref.fmf
  tests/core/fmf-id/data/remote-plan-with-invalid-ref.fmf
  tests/core/fmf-id/data/remote-plan-with-valid-ref.fmf
  tests/core/fmf-id/data/test-with-invalid-ref.fmf
  tests/core/fmf-id/data/test-with-valid-ref.fmf
  tests/core/fmf-id/main.fmf
  tests/core/fmf-id/test.sh
  tests/discover/data/plans.fmf
  tests/discover/references.sh
  tmt/base.py
  tmt/steps/discover/fmf.py
Labels: tests, schema

#1633 Adds an extra level of step data classes for provisioning and report
  tmt/steps/provision/__init__.py
  tmt/steps/provision/artemis.py
  tmt/steps/provision/connect.py
  tmt/steps/provision/local.py
  tmt/steps/provision/podman.py
  tmt/steps/provision/testcloud.py
  tmt/steps/report/__init__.py
  tmt/steps/report/html.py
  tmt/steps/report/junit.py
  tmt/steps/report/polarion.py
Labels: steps

#1632 Fix `/tests/run/shell` access permission problem
  tests/run/shell/test.sh
Labels: tests

#1499 Test for discover.shell tests
  tests/discover/data/plans.fmf
  tests/discover/main.fmf
  tests/discover/scripts.sh
  tests/discover/tests.sh
Labels: discover, tests

#1590 Enable context based plan parametrization
  docs/examples.rst
  tests/discover/data/plans.fmf
  tests/discover/parametrize.sh
  tmt/base.py
Labels: context, base

#1637 Add `SpecBasedContainer.to_minimal_spec()` method
  docs/classes.rst
  tmt/base.py
  tmt/steps/discover/__init__.py
  tmt/utils.py
Labels: code style

#1630 Support beaker libraries as recommended packages
  tests/unit/test_beakerlib.py
  tmt/base.py
  tmt/beakerlib.py
  tmt/steps/discover/shell.py
Labels: bug, libraries, breakage

#1636 Enable variable expansion for dynamic references
  docs/examples.rst
  tests/discover/data/dynamic-ref.fmf
  tests/discover/dynamic-ref.sh
  tmt/steps/discover/fmf.py
Labels: discover

#1526 Convert utils' Run unit tests to class-less tests
  docs/contribute.rst
  tests/unit/test_utils.py
Labels: tests

#1584 Update the overview of essential classes
  docs/classes.rst
Labels: documentation

#1589 Capture uncaught exceptions when using testcloud
  tmt/steps/provision/testcloud.py
Labels: testcloud

#1639 Fix getting CentOS via --how virtual
  tmt/steps/provision/testcloud.py
Labels: provision, testcloud

#1649 Handle dist-git-sources for gitlab
  tests/unit/test_utils.py
  tmt/utils.py
Labels: utils
