Repository teemtee/tmt, pull requests merged in 2022-03, with the labels that each got.

#1053 Prevent koji build failures on unsupported arches
  tmt.spec
Labels: packaging

#1100 Update documentation for plan parametrization
  docs/examples.rst
Labels: documentation

#1043 Updating module to allow for tmt import of 'metadata' file for #1002
  tests/test/import/data/parent/child/metadata
  tests/test/import/test.sh
  tmt/cli.py
  tmt/convert.py
Labels: import, tests, restraint

#932 Allow fmf-id to be exported from run discover
  tests/discover/filtering.sh
  tests/discover/options.sh
  tmt/base.py
  tmt/steps/discover/__init__.py
  tmt/steps/discover/fmf.py
  tmt/utils.py
Labels: discover, export

#1109 Update document for creating virtual environment
  docs/contribute.rst
Labels: documentation

#1110 Correcting regex read from restraint metadata file.
  tests/test/import/data/parent/child/metadata
  tests/test/import/test.sh
  tmt/convert.py
Labels: import

#1056 Build `epel9` packages, update install docs
  .packit.yaml
  README.rst
Labels: packaging, tests
