Repository teemtee/tmt, pull requests merged in 2022-07, with the labels that each got.

#1315 Fixes names of Artemis API versions - no prefixes, please
  tmt/steps/provision/artemis.py
Labels: bug, provision

#1313 Cache content of each loaded environment file
  tmt/base.py
  tmt/utils.py
Labels: environment

#1321 Require fresh testcloud with coreos support
  setup.py
  tmt.spec
Labels: packaging

#1318 Release tmt-1.15.0
  README.rst
  tmt.spec
Labels: packaging

#1330 Fix package installation using `rpm-ostree`
  tests/prepare/install/data/copr.fmf
  tests/prepare/install/data/debuginfo.fmf
  tests/prepare/install/data/epel7.fmf
  tests/prepare/install/data/escape.fmf
  tests/prepare/install/data/exclude.fmf
  tests/prepare/install/data/existing.fmf
  tests/prepare/install/data/main.fmf
  tests/prepare/install/data/missing.fmf
  tests/prepare/install/main.fmf
  tests/prepare/install/test.sh
  tmt/steps/prepare/install.py
Labels: prepare

#1177 Set the `1777` permision for `/var/tmp/tmt`
  tests/run/permissions/main.fmf
  tests/run/permissions/test.sh
  tmt.spec
  tmt/utils.py
Labels: utils

#1339 Remove duplicated short option in tmt lint
  tmt/options.py
Labels: cli

#1340 Support conditional requires with `pip` as well
  setup.py
Labels: packaging

#1342 Backwards compatibility for rstrnt-report-log
  spec/plans/execute.fmf
  stories/features/report-log.fmf
  tests/execute/restraint/report-log/data/.fmf/version
  tests/execute/restraint/report-log/data/log.fmf
  tests/execute/restraint/report-log/data/log.sh
  tests/execute/restraint/report-log/data/plan.fmf
  tests/execute/restraint/report-log/main.fmf
  tests/execute/restraint/report-log/test.sh
  tmt/steps/execute/internal.py
  tmt/steps/execute/scripts/tmt-file-submit
Labels: restraint

#1304 Add type annotations for tmt/options.py
  mypy.ini
  tmt/options.py
  tmt/steps/__init__.py
Labels: type annotations

#1319 Add typing for tmt/steps/report/__init__.py
  mypy.ini
  tmt/steps/__init__.py
  tmt/steps/discover/__init__.py
  tmt/steps/execute/__init__.py
  tmt/steps/finish/__init__.py
  tmt/steps/prepare/__init__.py
  tmt/steps/provision/__init__.py
  tmt/steps/report/__init__.py
Labels: type annotations

#1325 Add typing for tmt/steps/report/display.py
  mypy.ini
  tmt/steps/report/display.py
Labels: type annotations

#1324 Add typing for tmt/steps/report/html.py
  mypy.ini
  tmt/options.py
  tmt/steps/report/html.py
Labels: type annotations

#1323 Add typing for tmt/steps/report/junit.py
  mypy.ini
  tmt/steps/report/junit.py
Labels: report, type annotations

#1348 Remove duplicated keys when showing plugin details
  tmt/steps/discover/fmf.py
Labels: discover

#1259 tmt/convert.py: add typing
  mypy.ini
  tmt/convert.py
Labels: type annotations

#1327 Add typing for tmt/steps/execute/__init__.py
  mypy.ini
  tmt/steps/execute/__init__.py
Labels: type annotations

#1247 Convert guest implementations to use serializable container for load/save
  tests/multihost/provision/test.sh
  tmt/steps/provision/__init__.py
  tmt/steps/provision/artemis.py
  tmt/steps/provision/connect.py
  tmt/steps/provision/local.py
  tmt/steps/provision/podman.py
  tmt/steps/provision/testcloud.py
Labels: provision, type annotations

#1333 Add typing for steps/discover/__init__.py
  mypy.ini
  tmt/steps/__init__.py
  tmt/steps/discover/__init__.py
  tmt/steps/execute/__init__.py
Labels: type annotations

#1298 Add type annotations for tmt/export.py
  mypy.ini
  tmt/export.py
Labels: type annotations

#1306 Add type annotations for tmt/cli.py
  mypy.ini
  tmt/cli.py
  tmt/convert.py
  tmt/options.py
  tmt/utils.py
Labels: type annotations

#1209 Do not apply test command filter in upgrade
  tests/execute/upgrade/ignore_test.sh
  tests/execute/upgrade/main.fmf
  tmt/steps/execute/upgrade.py
  tmt/utils.py
Labels: execute

#1369 Support to lint attribute 'id'
  tests/plan/lint/data/good.fmf
  tests/story/lint/data/good.fmf
  tests/test/lint/data/good.fmf
  tmt/base.py
Labels: lint

#1337 Add Polarion report plugin
  mypy.ini
  setup.py
  tests/report/polarion/data/.fmf/version
  tests/report/polarion/data/main.fmf
  tests/report/polarion/main.fmf
  tests/report/polarion/test.sh
  tmt.spec
  tmt/base.py
  tmt/export.py
  tmt/schemas/report/polarion.yaml
  tmt/steps/execute/__init__.py
  tmt/steps/report/junit.py
  tmt/steps/report/polarion.py
Labels: report, polarion

#1376 Ask mypy to check whole tmt.steps.report package
  mypy.ini
Labels: type annotations

#931 Print result for execute -h tmt -v
  docs/examples.rst
  tests/execute/restraint/tmt-abort/test.sh
  tests/execute/result/data/test.fmf
  tests/execute/result/test.sh
  tmt/steps/execute/internal.py
Labels: execute

#1388 Add missing report specifications/docs
  spec/plans/report.fmf
Labels: documentation

#1293 Implement reboot reconnect timeout configuration
  stories/features/reboot.fmf
  tmt/steps/execute/internal.py
  tmt/steps/execute/scripts/tmt-reboot
  tmt/steps/provision/__init__.py
  tmt/steps/provision/local.py
  tmt/steps/provision/podman.py
  tmt/steps/provision/testcloud.py
Labels: execute, provision

#1390 Package schemas in subdirectories too
  setup.py
Labels: packaging

#1266 Schema loading helpers
  tests/unit/test_schemas.py
  tmt/utils.py
Labels: type annotations, code style

#1393 Update 'Develop' section of contribution docs
  docs/contribute.rst
Labels: documentation
