Repository teemtee/tmt, pull requests merged in 2023-09, with the labels that each got.

#2300 Make file/fmf dependencies hashable
  tmt/base.py
Labels: bug

#2241 Fix README and man page command
  README.rst
  docs/guide.rst
Labels: documentation

#2303 Render default friendly command for guest execution
  tmt/steps/provision/__init__.py
  tmt/steps/provision/local.py
  tmt/steps/provision/podman.py
Labels: provision, logging

#2217 Render `link` fields in tmt stories and specs
  docs/conf.py
  docs/story.rst.j2
  spec/hardware/compatible.fmf
  spec/hardware/cpu.fmf
  spec/hardware/network.fmf
  spec/hardware/tpm.fmf
  spec/plans/guest-topology.fmf
  spec/plans/import.fmf
  spec/plans/results.fmf
  spec/stories/priority.fmf
  spec/tests/duration.fmf
  spec/tests/manual.fmf
  stories/cli/test.fmf
  tmt/base.py
Labels: documentation

#2229 Separate value formatting from key/value nature of tmt.utils.format()
  tests/core/fmf-id/test.sh
  tests/plan/context/test.sh
  tests/plan/show/test.sh
  tests/test/import/test.sh
  tests/unit/test_utils.py
  tmt/base.py
  tmt/utils.py
Labels: utils, logging

#2078 Use `testcloud` domain API v2
  .packit.yaml
  setup.py
  tmt.spec
  tmt/steps/provision/testcloud.py
Labels: provision, testcloud

#2312 Release tmt-1.27.0
  README.rst
  tmt.spec
Labels: packaging

#2313 Fix output indentation of imported plans
  tmt/base.py
Labels: plans

#2310 Remove TBD of `initiator` context for Packit
  spec/context/initiator.fmf
Labels: specification

#2314 Adjust test coverage for deep beakerlib libraries
  tests/discover/libraries/data/file.sh
  tests/discover/libraries/test.sh
Labels: libraries, tmt tests

#2308 Disable `systemd-resolved` to prevent dns failures
  plans/main.fmf
Labels: tmt tests

#2327 Move check-related code into tmt.checks
  tests/test/check/test.sh
  tmt/base.py
  tmt/checks/__init__.py
  tmt/checks/dmesg.py
  tmt/steps/execute/__init__.py
Labels: execute, results, check

#2329 Lower unnecessary verbosity of podman commands
  tmt/steps/provision/podman.py
Labels: logging, containers

#2274 Wrap `click.Choice` use with `choices` parameter
  tmt/cli.py
  tmt/options.py
  tmt/steps/__init__.py
  tmt/utils.py
Labels: code style

#2261 Replace `pkg_resources` with `importlib.resources`
  tmt/export/__init__.py
  tmt/steps/execute/__init__.py
  tmt/steps/report/html.py
  tmt/utils.py
Labels: code style

#2281 Hide command event debug logs behind a log topic
  tests/execute/duration/test.sh
  tmt/log.py
  tmt/utils.py
Labels: logging

#2315 Make the upload to PyPI working again
  Makefile
  setup.py
Labels: packaging

#2277 Multi-string help texts converted to multiline strings
  tmt/cli.py
  tmt/options.py
  tmt/steps/discover/fmf.py
  tmt/steps/provision/__init__.py
  tmt/steps/provision/artemis.py
  tmt/steps/provision/mrack.py
  tmt/steps/provision/testcloud.py
  tmt/steps/report/display.py
  tmt/steps/report/html.py
  tmt/steps/report/polarion.py
  tmt/steps/report/reportportal.py
Labels: code style

#2288 Add the `export` callback for fields
  tmt/base.py
  tmt/utils.py
Labels: export, code style

#2292 Refactor exception rendering to use generators
  tmt/utils.py
Labels: logging, code style

#2341 Use the minimal plan to test imported plan execution
  tests/plan/import/basic.sh
Labels: tmt tests

#2319 Use `format_value()` instead of `pprint()`
  tmt/convert.py
  tmt/utils.py
Labels: logging, code style

#2306 Refactor parameters of `Plan._iter_steps()`
  tmt/base.py
  tmt/utils.py
Labels: code style

#2290 Narrow type of hardware constraint variants
  tmt/hardware.py
Labels: hardware, code style

#2280 Refactor html report plugin to use existing template rendering
  tmt/steps/report/html.py
  tmt/utils.py
Labels: report, html, code style

#2289 Use dataclass for log record details instead of typed dict
  tests/unit/__init__.py
  tests/unit/test_logging.py
  tmt/log.py
Labels: code style

#2294 Replace opt() for --dry/--force with properties
  tmt/base.py
  tmt/export/nitrate.py
  tmt/export/polarion.py
  tmt/steps/__init__.py
  tmt/steps/discover/fmf.py
  tmt/steps/execute/internal.py
  tmt/steps/execute/upgrade.py
  tmt/steps/finish/__init__.py
  tmt/steps/prepare/install.py
  tmt/steps/prepare/shell.py
  tmt/steps/provision/__init__.py
  tmt/steps/provision/podman.py
  tmt/steps/provision/testcloud.py
  tmt/steps/report/html.py
  tmt/utils.py
Labels: type annotations, code style

#2349 Stop using the `_version.py` file
  Makefile
  pyproject.toml
  tmt/__init__.py
  tmt/_version.py
Labels: packaging, no functional change

#2354 Include more dependencies in the test environment
  pyproject.toml
Labels: tmt tests

#2350 Adds nice & colorfull help to "make" targets
  Makefile
Labels: documentation

#2331 AVC denials check for tests
  tests/test/check/data/main.fmf
  tests/test/check/data/plan.fmf
  tests/test/check/main.fmf
  tests/test/check/test-avc.sh
  tests/test/check/test-dmesg.sh
  tmt/checks/avc.py
  tmt/steps/execute/internal.py
Labels: execute, tests, check

#2342 Create a production copr build for each release
  .packit.yaml
Labels: packaging

#2328 Always show the real beaker job id
  tmt/steps/provision/mrack.py
Labels: provision, mrack

#2344 Extract beakerlib phase name to a failure log
  tmt/result.py
Labels: report

#2336 Add a new `cpu` property `stepping` to hardware
  spec/hardware/cpu.fmf
  tmt/schemas/provision/hardware.yaml
Labels: specification, hardware

#2358 Move the copr repository to the `teemtee` group
  .packit.yaml
  README.rst
Labels: packaging

#2321 Include link to the data directory in the html report
  spec/plans/results.fmf
  tmt/base.py
  tmt/result.py
  tmt/steps/execute/internal.py
  tmt/steps/report/html/template.html.j2
Labels: report, html, results

#2324 Beaker plugin is negating Beaker operators by default
  tmt/steps/provision/mrack.py
Labels: bug, hardware, mrack
