Repository teemtee/tmt, pull requests merged in 2023-05, with the labels that each got.

#2025 Fix duplicate export for Polarion hyperlinks
  tmt/export/polarion.py
Labels: bug, export, polarion, ready for merge

#1755 Add a new cpu property `flag` to the hardware spec
  spec/hardware/cpu.fmf
  tmt/schemas/provision/hardware.yaml
Labels: specification, hardware, ready for merge

#2041 Replace '--t' by '-t' when creating a new plan with template
  docs/examples.rst
Labels: documentation, ready for merge

#2037 Drop some no longer valid TODO comments
  tmt/base.py
  tmt/export/__init__.py
  tmt/result.py
  tmt/schemas/story.yaml
  tmt/steps/prepare/shell.py
  tmt/steps/provision/artemis.py
  tmt/steps/report/display.py
Labels: no functional change

#2043 Fix ruamel.yaml type waivers that mypy sometimes ignores
  tmt/utils.py
Labels: type annotations

#1929 Improve names and docs around CLI context in Common classes
  tests/integration/test_nitrate.py
  tmt/base.py
  tmt/cli.py
  tmt/steps/__init__.py
  tmt/steps/discover/__init__.py
  tmt/steps/discover/fmf.py
  tmt/steps/execute/__init__.py
  tmt/steps/execute/upgrade.py
  tmt/steps/finish/__init__.py
  tmt/steps/prepare/__init__.py
  tmt/steps/provision/__init__.py
  tmt/steps/report/__init__.py
  tmt/utils.py
Labels: code style

#1840 Refactor logging during plugin discovery, using tmt's logging
  bin/tmt
  docs/conf.py
  tests/core/env/test.sh
  tests/unit/test_schemas.py
  tests/unit/test_utils.py
  tmt/base.py
  tmt/cli.py
  tmt/plugins/__init__.py
  tmt/steps/__init__.py
  tmt/steps/provision/__init__.py
  tmt/utils.py
Labels: plugins, logging

#1531 Correct the path of Ansible playbook
  docs/examples.rst
  examples/multiple/basic.fmf
  tests/lint/data/plans/bad.fmf
  tests/lint/data/plans/good.fmf
  tmt/templates.py
Labels: documentation

#2051 Shorter Nitrate summary name
  tests/integration/test_nitrate.py
  tmt/cli.py
  tmt/export/nitrate.py
  tmt/export/polarion.py
Labels: export, nitrate, polarion

#2036 Convert gitlab private namespace into dist-git url
  tests/unit/test_utils.py
  tmt/utils.py
Labels: export

#1999 Unify examples of results in test and plan specification
  spec/plans/results.fmf
  spec/tests/result.fmf
Labels: documentation, no functional change

#1791 Implement `deprecated` for obsoleted options
  tmt/utils.py
Labels: utils, cli

#1911 Add test start/end timestamps into results
  spec/plans/results.fmf
  tests/execute/result/custom.sh
  tests/unit/test_utils.py
  tmt/base.py
  tmt/result.py
  tmt/schemas/common.yaml
  tmt/schemas/results.yaml
  tmt/steps/execute/__init__.py
  tmt/steps/execute/internal.py
Labels: execute, results

#1932 Explore all available plugins only once
  docs/examples.rst
  tmt/plugins/__init__.py
Labels: plugins, base

#2055 Request newer os image and python version for docs
  .readthedocs.yaml
Labels: documentation

#1851 Refactored metadata linting
  tests/lint/test.sh
  tests/plan/lint/main.fmf
  tests/plan/lint/test.sh
  tests/precommit/test.sh
  tests/story/lint/test.sh
  tests/test/lint/test.sh
  tmt/base.py
  tmt/cli.py
  tmt/lint.py
  tmt/options.py
Labels: must, lint

#2023 Print only failed objects when linting in hook
  .pre-commit-hooks.yaml
  tests/precommit/test.sh
Labels: pre-commit

#2077 Release tmt-1.23.0
  README.rst
  docs/guide.rst
  tmt.spec
Labels: packaging

#2081 Require setuptools
  setup.py
  tests/prepare/basic/data/main.fmf
  tests/prepare/basic/test.sh
Labels: packaging, must, ready for merge

#2083 Support urllib3 2.x and its allowed_methods/method_whitelist
  tmt/utils.py
Labels: ready for merge

#1890 Formalizing guest "facts" storage
  tests/login/step.sh
  tests/provision/facts/main.fmf
  tests/provision/facts/test.sh
  tmt/steps/prepare/install.py
  tmt/steps/provision/__init__.py
Labels: provision, blocking other work, results, ready for merge

#1790 Parallelize prepare and execute steps
  README.rst
  tests/login/step.sh
  tests/multihost/complete/data/.fmf/version
  tests/multihost/complete/data/plans.fmf
  tests/multihost/complete/data/tests/C/main.fmf
  tests/multihost/complete/data/tests/main.fmf
  tests/multihost/complete/data/tests/test.sh
  tests/multihost/complete/main.fmf
  tests/multihost/complete/test.sh
  tests/multihost/corner-cases/data/.fmf/version
  tests/multihost/corner-cases/data/plans.fmf
  tests/multihost/corner-cases/main.fmf
  tests/multihost/corner-cases/test.sh
  tests/multihost/web/data/plan.fmf
  tests/multihost/web/data/test.fmf
  tmt/queue.py
  tmt/steps/__init__.py
  tmt/steps/discover/__init__.py
  tmt/steps/discover/fmf.py
  tmt/steps/discover/shell.py
  tmt/steps/execute/__init__.py
  tmt/steps/execute/internal.py
  tmt/steps/execute/upgrade.py
  tmt/steps/finish/__init__.py
  tmt/steps/prepare/__init__.py
  tmt/steps/prepare/multihost.py
  tmt/steps/prepare/shell.py
Labels: execute, prepare, must, multihost, blocking other work, highlight

#2038 Replaces "common" object with logger in method hint logging
  tmt/options.py
  tmt/steps/__init__.py
Labels: logging, code style, ready for merge

#2076 Handle el6 as a legacy os too in virtual provision
  tmt/steps/provision/testcloud.py
Labels: testcloud, ready for merge

#2101 Make tmt test wrapper name unique to avoid race conditions
  tmt/steps/execute/internal.py
Labels: bug, multihost

#2109 Test data path must use safe guest/test names
  tmt/steps/execute/__init__.py
  tmt/utils.py
Labels: bug, ready for merge

#2094 Crashed prepare and execute steps propagate all causes
  tmt/steps/execute/__init__.py
  tmt/steps/prepare/__init__.py
Labels: multihost

#2080 Convert base classes to data classes
  tmt/base.py
  tmt/steps/__init__.py
  tmt/steps/execute/internal.py
  tmt/utils.py
Labels: base, code style, no functional change

#2110 Turn finish step implementation to queue-based one
  tmt/steps/__init__.py
  tmt/steps/finish/__init__.py
  tmt/steps/prepare/__init__.py
Labels: finish, multihost

#2105 Use the `tmt-lint` pre-commit hook
  .pre-commit-config.yaml
Labels: tmt tests

#2099 Rename Require* classes to Dependency*
  docs/classes.rst
  tests/unit/test_beakerlib.py
  tests/unit/test_file_require.py
  tmt/base.py
  tmt/libraries/__init__.py
  tmt/libraries/beakerlib.py
  tmt/libraries/file.py
  tmt/steps/__init__.py
  tmt/steps/discover/__init__.py
  tmt/steps/discover/shell.py
  tmt/steps/execute/internal.py
  tmt/steps/prepare/__init__.py
  tmt/steps/prepare/install.py
  tmt/steps/provision/__init__.py
Labels: breakage, code style
